# Generated by gallery/generate.py; do not edit.
# Cell 1: Clear glass: isolated cube and 3x3 wall
setblock 192 101 205 connectedglass:clear_glass replace
setblock 195 101 209 connectedglass:clear_glass replace
setblock 196 101 209 connectedglass:clear_glass replace
setblock 197 101 209 connectedglass:clear_glass replace
setblock 195 102 209 connectedglass:clear_glass replace
setblock 196 102 209 connectedglass:clear_glass replace
setblock 197 102 209 connectedglass:clear_glass replace
setblock 195 103 209 connectedglass:clear_glass replace
setblock 196 103 209 connectedglass:clear_glass replace
setblock 197 103 209 connectedglass:clear_glass replace
