# Generated by gallery/generate.py; do not edit.
# Cell 2: Scratched red glass: L wall with missing diagonal
setblock 210 101 208 connectedglass:scratched_glass_red replace
setblock 211 101 208 connectedglass:scratched_glass_red replace
setblock 212 101 208 connectedglass:scratched_glass_red replace
setblock 210 102 208 connectedglass:scratched_glass_red replace
setblock 210 103 208 connectedglass:scratched_glass_red replace
setblock 211 102 208 minecraft:air replace
