# Generated by gallery/generate.py; do not edit.
# Cell 3: Tinted borderless glass: 2x2 beside stone
setblock 226 101 208 connectedglass:tinted_borderless_glass replace
setblock 227 101 208 connectedglass:tinted_borderless_glass replace
setblock 226 102 208 connectedglass:tinted_borderless_glass replace
setblock 227 102 208 connectedglass:tinted_borderless_glass replace
setblock 228 101 208 minecraft:stone replace
setblock 229 101 208 minecraft:stone replace
setblock 228 102 208 minecraft:stone replace
setblock 229 102 208 minecraft:stone replace
