# Generated by gallery/generate.py; do not edit.
# Cell 4: Mixed clear, colored, and borderless cube boundary
setblock 241 101 208 connectedglass:clear_glass replace
setblock 242 101 208 connectedglass:clear_glass replace
setblock 243 101 208 connectedglass:clear_glass_red replace
setblock 244 101 208 connectedglass:borderless_glass replace
