# Generated by gallery/generate.py; do not edit.
# Cell 5: Clear pane: isolated, straight, L, T, and cross
setblock 192 101 220 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] replace
setblock 192 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 192 101 225 connectedglass:clear_glass_pane[east=false,north=true,south=true,waterlogged=false,west=false] replace
setblock 192 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 196 101 220 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 196 101 221 connectedglass:clear_glass_pane[east=true,north=true,south=false,waterlogged=false,west=false] replace
setblock 197 101 221 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 196 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=false,waterlogged=false,west=true] replace
setblock 196 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 197 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 195 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
setblock 200 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=true,waterlogged=false,west=true] replace
setblock 200 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 201 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 200 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 199 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
