# Generated by gallery/generate.py; do not edit.
# Cell 6: Borderless red pane: two-high straight and cross stacks
setblock 208 101 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 208 102 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 208 101 224 connectedglass:borderless_glass_red_pane[east=false,north=true,south=true,waterlogged=false,west=false] replace
setblock 208 102 224 connectedglass:borderless_glass_red_pane[east=false,north=true,south=true,waterlogged=false,west=false] replace
setblock 208 101 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 208 102 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 215 101 224 connectedglass:borderless_glass_red_pane[east=true,north=true,south=true,waterlogged=false,west=true] replace
setblock 215 101 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 216 101 224 connectedglass:borderless_glass_red_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 215 101 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 214 101 224 connectedglass:borderless_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
setblock 215 102 224 connectedglass:borderless_glass_red_pane[east=true,north=true,south=true,waterlogged=false,west=true] replace
setblock 215 102 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 216 102 224 connectedglass:borderless_glass_red_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 215 102 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 214 102 224 connectedglass:borderless_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
