# Generated by gallery/generate.py; do not edit.
# Cell 7: Mixed pane boundary and contained waterlogged pane
setblock 224 101 221 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
setblock 225 101 221 connectedglass:clear_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=true] replace
setblock 226 101 221 connectedglass:borderless_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 230 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] replace
setblock 231 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] replace
setblock 230 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] replace
setblock 229 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] replace
setblock 230 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=true,waterlogged=true,west=true] replace
