# Generated by gallery/generate.py; do not edit.
# Cell 8: Vanilla glass, pane, and stone controls
setblock 240 101 224 minecraft:glass replace
setblock 241 101 224 minecraft:glass replace
setblock 244 101 224 minecraft:glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] replace
setblock 248 101 224 minecraft:stone replace
