# Generated by gallery/generate.py; do not edit.
scoreboard objectives add cg_gallery dummy
function connectedglass_gallery:clear
execute in minecraft:overworld run fill 190 100 202 202 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 191 100 203 201 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/01_clear_glass_wall
execute in minecraft:overworld run fill 206 100 202 218 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 207 100 203 217 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/02_scratched_red_l
execute in minecraft:overworld run fill 222 100 202 234 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 223 100 203 233 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/03_tinted_beside_stone
execute in minecraft:overworld run fill 238 100 202 250 100 214 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 239 100 203 249 100 213 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/04_mixed_cube_boundary
execute in minecraft:overworld run fill 190 100 218 202 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 191 100 219 201 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/05_clear_pane_topologies
execute in minecraft:overworld run fill 206 100 218 218 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 207 100 219 217 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/06_red_pane_stacks
execute in minecraft:overworld run fill 222 100 218 234 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 223 100 219 233 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/07_mixed_and_waterlogged_panes
execute in minecraft:overworld run fill 238 100 218 250 100 230 minecraft:deepslate_tiles replace
execute in minecraft:overworld run fill 239 100 219 249 100 229 minecraft:smooth_stone replace
execute in minecraft:overworld run function connectedglass_gallery:cell_build/08_vanilla_controls
scoreboard players set #cells cg_gallery 8
scoreboard players set #placements cg_gallery 71
scoreboard players set #observations cg_gallery 72
scoreboard players set #ready cg_gallery 1
function connectedglass_gallery:verify
