# Generated by gallery/generate.py; do not edit.
execute in minecraft:overworld run forceload add 189 201 251 231
execute in minecraft:overworld run fill 189 100 201 251 106 231 minecraft:air replace
