# Generated by gallery/generate.py; do not edit.
scoreboard players set #checked cg_gallery 0
scoreboard players set #failed_cells cg_gallery 0
scoreboard players set #failures cg_gallery 0
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/01_clear_glass_wall
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/02_scratched_red_l
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/03_tinted_beside_stone
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/04_mixed_cube_boundary
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/05_clear_pane_topologies
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/06_red_pane_stacks
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/07_mixed_and_waterlogged_panes
execute in minecraft:overworld run function connectedglass_gallery:cell_verify/08_vanilla_controls
function connectedglass_gallery:status
execute if score #failures cg_gallery matches 0 run tellraw @a {"color":"green","text":"Connected Glass gallery verification passed."}
execute unless score #failures cg_gallery matches 0 run tellraw @a {"color":"red","text":"Connected Glass gallery verification failed."}
