# Generated by gallery/generate.py; do not edit.
# Cell 1: Clear glass: isolated cube and 3x3 wall
scoreboard players set #case01 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 192 101 205 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 192 101 205 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 195 101 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 195 101 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 101 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 196 101 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 197 101 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 197 101 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 195 102 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 195 102 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 102 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 196 102 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 197 102 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 197 102 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 195 103 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 195 103 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 103 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 196 103 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 197 103 209 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 197 103 209 connectedglass:clear_glass run scoreboard players add #case01 cg_gallery 1
execute if score #case01 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case01 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 1 failed: Clear glass: isolated cube and 3x3 wall"}
