# Generated by gallery/generate.py; do not edit.
# Cell 2: Scratched red glass: L wall with missing diagonal
scoreboard players set #case02 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 210 101 208 connectedglass:scratched_glass_red run scoreboard players add #failures cg_gallery 1
execute unless block 210 101 208 connectedglass:scratched_glass_red run scoreboard players add #case02 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 211 101 208 connectedglass:scratched_glass_red run scoreboard players add #failures cg_gallery 1
execute unless block 211 101 208 connectedglass:scratched_glass_red run scoreboard players add #case02 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 212 101 208 connectedglass:scratched_glass_red run scoreboard players add #failures cg_gallery 1
execute unless block 212 101 208 connectedglass:scratched_glass_red run scoreboard players add #case02 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 210 102 208 connectedglass:scratched_glass_red run scoreboard players add #failures cg_gallery 1
execute unless block 210 102 208 connectedglass:scratched_glass_red run scoreboard players add #case02 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 210 103 208 connectedglass:scratched_glass_red run scoreboard players add #failures cg_gallery 1
execute unless block 210 103 208 connectedglass:scratched_glass_red run scoreboard players add #case02 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 211 102 208 minecraft:air run scoreboard players add #failures cg_gallery 1
execute unless block 211 102 208 minecraft:air run scoreboard players add #case02 cg_gallery 1
execute if score #case02 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case02 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 2 failed: Scratched red glass: L wall with missing diagonal"}
