# Generated by gallery/generate.py; do not edit.
# Cell 3: Tinted borderless glass: 2x2 beside stone
scoreboard players set #case03 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 226 101 208 connectedglass:tinted_borderless_glass run scoreboard players add #failures cg_gallery 1
execute unless block 226 101 208 connectedglass:tinted_borderless_glass run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 227 101 208 connectedglass:tinted_borderless_glass run scoreboard players add #failures cg_gallery 1
execute unless block 227 101 208 connectedglass:tinted_borderless_glass run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 226 102 208 connectedglass:tinted_borderless_glass run scoreboard players add #failures cg_gallery 1
execute unless block 226 102 208 connectedglass:tinted_borderless_glass run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 227 102 208 connectedglass:tinted_borderless_glass run scoreboard players add #failures cg_gallery 1
execute unless block 227 102 208 connectedglass:tinted_borderless_glass run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 228 101 208 minecraft:stone run scoreboard players add #failures cg_gallery 1
execute unless block 228 101 208 minecraft:stone run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 229 101 208 minecraft:stone run scoreboard players add #failures cg_gallery 1
execute unless block 229 101 208 minecraft:stone run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 228 102 208 minecraft:stone run scoreboard players add #failures cg_gallery 1
execute unless block 228 102 208 minecraft:stone run scoreboard players add #case03 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 229 102 208 minecraft:stone run scoreboard players add #failures cg_gallery 1
execute unless block 229 102 208 minecraft:stone run scoreboard players add #case03 cg_gallery 1
execute if score #case03 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case03 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 3 failed: Tinted borderless glass: 2x2 beside stone"}
