# Generated by gallery/generate.py; do not edit.
# Cell 4: Mixed clear, colored, and borderless cube boundary
scoreboard players set #case04 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 241 101 208 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 241 101 208 connectedglass:clear_glass run scoreboard players add #case04 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 242 101 208 connectedglass:clear_glass run scoreboard players add #failures cg_gallery 1
execute unless block 242 101 208 connectedglass:clear_glass run scoreboard players add #case04 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 243 101 208 connectedglass:clear_glass_red run scoreboard players add #failures cg_gallery 1
execute unless block 243 101 208 connectedglass:clear_glass_red run scoreboard players add #case04 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 244 101 208 connectedglass:borderless_glass run scoreboard players add #failures cg_gallery 1
execute unless block 244 101 208 connectedglass:borderless_glass run scoreboard players add #case04 cg_gallery 1
execute if score #case04 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case04 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 4 failed: Mixed clear, colored, and borderless cube boundary"}
