# Generated by gallery/generate.py; do not edit.
# Cell 5: Clear pane: isolated, straight, L, T, and cross
scoreboard players set #case05 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 192 101 220 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 192 101 220 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 192 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 192 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 192 101 225 connectedglass:clear_glass_pane[east=false,north=true,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 192 101 225 connectedglass:clear_glass_pane[east=false,north=true,south=true,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 192 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 192 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 101 220 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 196 101 220 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 101 221 connectedglass:clear_glass_pane[east=true,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 196 101 221 connectedglass:clear_glass_pane[east=true,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 197 101 221 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 197 101 221 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 196 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=false,waterlogged=false,west=true] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 196 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 196 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 197 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 197 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 195 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 195 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 200 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=true,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 200 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=true,waterlogged=false,west=true] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 200 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 200 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 201 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 201 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 200 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 200 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 199 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 199 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case05 cg_gallery 1
execute if score #case05 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case05 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 5 failed: Clear pane: isolated, straight, L, T, and cross"}
