# Generated by gallery/generate.py; do not edit.
# Cell 6: Borderless red pane: two-high straight and cross stacks
scoreboard players set #case06 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 208 101 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 208 101 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 208 102 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 208 102 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 208 101 224 connectedglass:borderless_glass_red_pane[east=false,north=true,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 208 101 224 connectedglass:borderless_glass_red_pane[east=false,north=true,south=true,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 208 102 224 connectedglass:borderless_glass_red_pane[east=false,north=true,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 208 102 224 connectedglass:borderless_glass_red_pane[east=false,north=true,south=true,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 208 101 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 208 101 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 208 102 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 208 102 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 215 101 224 connectedglass:borderless_glass_red_pane[east=true,north=true,south=true,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 215 101 224 connectedglass:borderless_glass_red_pane[east=true,north=true,south=true,waterlogged=false,west=true] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 215 101 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 215 101 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 216 101 224 connectedglass:borderless_glass_red_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 216 101 224 connectedglass:borderless_glass_red_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 215 101 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 215 101 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 214 101 224 connectedglass:borderless_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 214 101 224 connectedglass:borderless_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 215 102 224 connectedglass:borderless_glass_red_pane[east=true,north=true,south=true,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 215 102 224 connectedglass:borderless_glass_red_pane[east=true,north=true,south=true,waterlogged=false,west=true] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 215 102 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 215 102 223 connectedglass:borderless_glass_red_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 216 102 224 connectedglass:borderless_glass_red_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 216 102 224 connectedglass:borderless_glass_red_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 215 102 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 215 102 225 connectedglass:borderless_glass_red_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 214 102 224 connectedglass:borderless_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 214 102 224 connectedglass:borderless_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case06 cg_gallery 1
execute if score #case06 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case06 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 6 failed: Borderless red pane: two-high straight and cross stacks"}
