# Generated by gallery/generate.py; do not edit.
# Cell 7: Mixed pane boundary and contained waterlogged pane
scoreboard players set #case07 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 224 101 221 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 224 101 221 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 225 101 221 connectedglass:clear_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 225 101 221 connectedglass:clear_glass_red_pane[east=true,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 226 101 221 connectedglass:borderless_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 226 101 221 connectedglass:borderless_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 230 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 230 101 224 connectedglass:clear_glass_pane[east=false,north=false,south=true,waterlogged=false,west=false] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 231 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 231 101 225 connectedglass:clear_glass_pane[east=false,north=false,south=false,waterlogged=false,west=true] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 230 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 230 101 226 connectedglass:clear_glass_pane[east=false,north=true,south=false,waterlogged=false,west=false] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 229 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 229 101 225 connectedglass:clear_glass_pane[east=true,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case07 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 230 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=true,waterlogged=true,west=true] run scoreboard players add #failures cg_gallery 1
execute unless block 230 101 225 connectedglass:clear_glass_pane[east=true,north=true,south=true,waterlogged=true,west=true] run scoreboard players add #case07 cg_gallery 1
execute if score #case07 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case07 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 7 failed: Mixed pane boundary and contained waterlogged pane"}
