# Generated by gallery/generate.py; do not edit.
# Cell 8: Vanilla glass, pane, and stone controls
scoreboard players set #case08 cg_gallery 0
scoreboard players add #checked cg_gallery 1
execute unless block 240 101 224 minecraft:glass run scoreboard players add #failures cg_gallery 1
execute unless block 240 101 224 minecraft:glass run scoreboard players add #case08 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 241 101 224 minecraft:glass run scoreboard players add #failures cg_gallery 1
execute unless block 241 101 224 minecraft:glass run scoreboard players add #case08 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 244 101 224 minecraft:glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #failures cg_gallery 1
execute unless block 244 101 224 minecraft:glass_pane[east=false,north=false,south=false,waterlogged=false,west=false] run scoreboard players add #case08 cg_gallery 1
scoreboard players add #checked cg_gallery 1
execute unless block 248 101 224 minecraft:stone run scoreboard players add #failures cg_gallery 1
execute unless block 248 101 224 minecraft:stone run scoreboard players add #case08 cg_gallery 1
execute if score #case08 cg_gallery matches 1.. run scoreboard players add #failed_cells cg_gallery 1
execute if score #case08 cg_gallery matches 1.. run tellraw @a {"color":"red","text":"Connected Glass gallery cell 8 failed: Vanilla glass, pane, and stone controls"}
