apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluemap-sophisticated-review-public
  namespace: bluemap-sophisticated-staging
  labels:
    app.kubernetes.io/name: bluemap-connectedglass-review-public
    app.kubernetes.io/part-of: bluemap-sophisticated-staging
    bluemap.guenter.cloud/experiment-id: atm120-connectedglass-owner-review
spec:
  ingressClassName: traefik
  rules:
    - host: bluemap-connectedglass.guenter.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minecraft
                port:
                  name: bluemap
